### ISSUE TITLE
Allow platform extensions in preprocessors

### ISSUE THREAD

**Issue by birkir** [kristerkari/react-native-css-modules#12]
Currently the import system for each supported preprocessor works independently, so we won't get the features from metro bundler built in.

It would be great to be able to do something like this:

```scss
// variables.ios.scss
$primary-color: blue;

// variables.android.scss
$primary-color: red;

// helloworld.scss
@include 'variables.scss';

.helloWorld {
  color: $primary-color;
}
```

Which would result in `blue` color for android and `red` color for ios.

It would be great to be able to use metros resolver for this, but second option would be to implement extension to each preprocessors resolver somehow.

Note: platform extensions work when importing from JavaScript, this issue is about within an css file.
